<?xml version="1.0"?>
<package format="3">
  <name>sign_truck</name>
  <version>0.1.0</version>
  <description>Temporary panorama signal-vehicle detector.</description>
  <maintainer email="ssc@example.com">ssc</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
