tl_crop_only:
  ros__parameters:
    model_path: "yolo11s.pt"
    image_topic: "/zed/zed_node/left/image_rect_color"
    pub_hist_image: false
    show_windows: false

    roi_top_ratio:    0.00
    roi_bottom_ratio: 0.50
    roi_left_ratio:   0.25
    roi_right_ratio:  0.75

    min_side_px: 10
    min_area_px: 150
    aspect_min: 1.15
    aspect_max: 3.00
    edge_margin_px: 2

    s_min: 60
    v_min: 70
    min_valid_pixels: 1
    score_threshold: 0.20

    morph_close_iter: 1
    morph_open_iter:  0
    dilate_iter:      1

    ema_tau_s: 0.25
    majority_k: 5
    hold_ms: 300
    hysteresis_delta: 0.08
    missing_timeout_ms: 400

    red_lo1: 0
    red_hi1: 5
    red_lo2: 168
    red_hi2: 179
    yel_lo: 10
    yel_hi: 35
    grn_lo: 40
    grn_hi: 90

    max_h_w_ratio: 1.5

    lt_rule_enable: true
    lt_r_min: 0.55
    lt_g_min: 0.03
    lt_y_max: 0.02
    lt_valid_min: 20
